name: 'S3 Utility'
description: 'Execute various s3 (ls, sync, rm) and s3 helper commands (exists)'
author: 'The Events Calendar (support@theeventscalendar.com)'
branding:
  icon: file
  color: blue
outputs:
  exists:
    description: With the exists s3 helper command - \'true\' if file or directory exists, \'false\' otherwise
  ls_output:
    description: Output from \'aws s3 ls\' command
runs:
  using: 'docker'
  image: 'Dockerfile'
